<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Usuario;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsuarioSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Usuarios');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuario-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Usuario'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'idusuario',
            'login',
            'idorganizacion',
            [
                'header' => 'Grupos',
                'value' => function($data){
                    $data instanceof Usuario;
                    $return = "<ul>";
                    if ($data->idGrupos != null && count($data->idGrupos) > 0)
                    {
                        foreach ($data->idGrupos as $grupo)
                        {
                            $return = $return . "<li>" . Html::a($grupo->nombre, ['/admin/grupo/view', 'id' => $grupo->id_grupo]) . "</li>";
                        }
                    }
                    return $return . "</ul>";
                },
                'format' => 'raw',
            ],
            // 'persona',
            // 'accaplicacion',
            // 'accorganizacion',
            // 'accestructura',
            // 'acccambiofecha',
            // 'accusuario',
            // 'accpersona',
            // 'acccambioefiscal',
            // 'acciva',
            // 'accut',
            // 'accdesbloquear',
            // 'accdesconectar',
            // 'acctasaactiva',
            // 'accusuariocat',
            // 'accfichacat',
            // 'accvalorterrecat',
            // 'accvalortipocat',
            // 'accdepreciacioncat',
            // 'accrepcedcat',
            // 'accrepceremp',
            // 'accrepfichacat',
            // 'accrepgenseccat',
            // 'acccontribuyente',
            // 'accactividad',
            // 'accdeclaraciones',
            // 'accedocuenta',
            // 'accconfigcome',
            // 'accusuariocome',
            // 'accreppatente',
            // 'accimpedoctasectcome',
            // 'accrepgensector',
            // 'accrepactividad',
            // 'accrepfecdecla',
            // 'accrepmondecla',
            // 'accimppatente',
            // 'accinmueble',
            // 'accedoctainmue',
            // 'accvalfisterre',
            // 'accvalfiscons',
            // 'accconfiginmue',
            // 'accusuarioinmue',
            // 'accusrepsectcat',
            // 'accusrepmontaval',
            // 'accusreptipconstruc',
            // 'accusrepmontdeud',
            // 'accusrepvalorconstruc',
            // 'accimpedoctasectinmue',
            // 'accapuesta',
            // 'accclaseapuesta',
            // 'accedoctaapuesta',
            // 'accconfigapuesta',
            // 'accusuarioapuesta',
            // 'accvehiculo',
            // 'accclasevehiculo',
            // 'accedoctavehiculo',
            // 'accconfigvehiculo',
            // 'accusuariovehiculo',
            // 'accrepgenvehi',
            // 'accrepcontvehideud',
            // 'accreptipvehi',
            // 'accpublicidad',
            // 'accclasepublicidad',
            // 'accedoctapublicidad',
            // 'accconfigpublicidad',
            // 'accusuariopublicidad',
            // 'accrepgensecpubli',
            // 'accrepcontpublideud',
            // 'accreptippubli',
            // 'accrepedoctapubli',
            // 'accrenta',
            // 'accedoctarenta',
            // 'accconfigrenta',
            // 'accusuariorenta',
            // 'accefiscal',
            // 'acccatpro',
            // 'accpuc',
            // 'acccrearfactura',
            // 'accanularfactura',
            // 'accusuariofactura',
            // 'acctiporenta',
            // 'accrepgenrenta',
            // 'accurepcontratorenta',
            // 'accrepdeudarenta',
            // 'accrepedoctarenta',
            // 'accreptiporenta',
            // 'accbanco',
            // 'acccuentabancaria',
            // 'numcaja',
            // 'accusuariopresu',
            // 'accformpresu',
            // 'accaprobpresup',
            // 'accreppuc',
            // 'accrepformpresu',
            // 'accreppresuing',
            // 'accrepedofinanc',
            // 'accrepmovpresu',
            // 'accrepcondicpar',
            // 'accrepcomprom',
            // 'accpartext',
            // 'accaumentopart',
            // 'accdisminucionpart',
            // 'acctraslado',
            // 'acccompromiso',
            // 'accfacturar',
            // 'accanularfact',
            // 'accusuariofacturacion',
            // 'accrepfactemit',
            // 'accurepfactporcobrar',
            // 'accrepfactcobrada',
            // 'accrepfactanulada',
            // 'accrepfactportipo',
            // 'accingresos',
            // 'accsupervisor',
            // 'accrepresumcaja',
            // 'accreptransdiarias',
            // 'accrepactutransac',
            // 'accreptransacciones',
            // 'accrepcontrolcheq',
            // 'accrepcontroldepo',
            // 'accusuariocaja',
            // 'acctipoingreso',
            // 'acctipoimpuesto',
            // 'accrepconstancia',
            // 'accrepvalconstruc',
            // 'accrepvalterreno',
            // 'accrepdepreciacion',
            // 'accreptipoapuesta',
            // 'accrepgensectapu',
            // 'accrepdeclanualapu',
            // 'accrepdeudapuesta',
            // 'accrepedoctapuesta',
            // 'accactudeuindustria',
            // 'accactudeuinmue',
            // 'accactudeurenta',
            // 'accactudeuvehiculo',
            // 'accactudeuapuesta',
            // 'acctasapasiva',
            // 'accgestores',
            // 'accasignacion',
            // 'accvisitas',
            // 'accefectividad',
            // 'accrepresucaja',
            // 'accreptransadia',
            // 'accrepmovactu',
            // 'accrepdeudaperi',
            // 'accrepfactuasigna',
            // 'accrepdeudarecu',
            // 'accusuariogestion',
            // 'acclicores',
            // 'actipotasa',
            // 'accedoctalicores',
            // 'accconfiglicores',
            // 'accusuariolicores',
            // 'accrepgenseclicor',
            // 'accrepcontlicores',
            // 'accreptipotasa',
            // 'accrepedoctalicores',
            // 'accexplicores',
            // 'acctiporetencion',
            // 'accusuarioadmini',
            // 'accegresos',
            // 'acctransferenciabanc',
            // 'accconciliacion',
            // 'acccheqanul',
            // 'accdebito',
            // 'acccredito',
            // 'acccausar',
            // 'accaproborden',
            // 'accrepordenpago',
            // 'accrepbanco',
            // 'accrepretencion',
            // 'accrepfondoterc',
            // 'accdeposito',
            // 'accfondotercero',
            // 'accpagoordenes',
            // 'accregobras',
            // 'accusuarioingenieria',
            // 'accasigobras',
            // 'acccaratula',
            // 'acccuaderno',
            // 'accrepgenobras',
            // 'accrepobrasasig',
            // 'accrepobraejecu',
            // 'accrepcontratista',
            // 'acccamstainmue',
            // 'acccontratista',
            // 'acccargos',
            // 'accactivos',
            // 'accaprocompro',
            // 'accalmacen',
            // 'accsolisuministro',
            // 'accunimedi',
            // 'accproveedor',
            // 'acctipoproducto',
            // 'accproducto',
            // 'accrequisicion',
            // 'accsolicompra',
            // 'accaprosolicompra',
            // 'accusuariocompra',
            // 'accrepalmacen',
            // 'accreprespalmacen',
            // 'accrepsolicompra',
            // 'accrepsolisumi',
            // 'accreprequisicion',
            // 'acccontrolinterno',
            // 'acccuentacontable',
            // 'accaprobpagoobras',
            // 'accsolicpagoobras',
            // 'accubicacionalmacen',
            // 'accentradaalmacen',
            // 'accsalidaalmacen',
            // 'accdespachoalmacen',
            // 'acclisgencompraalmacen',
            // 'acclismovcompraalmacen',
            // 'acclisinventario',
            // 'acclissolicompraalmacen',
            // 'accaprodesaprodespacho',
            // 'accespecial',
            // 'accrepresugenobra',
            // 'accusuarionomina',
            // 'accpermdecla',
            // 'accacreditacion',
            // 'acctipomulta',
            // 'accmultaindu',
            // 'accmultainmu',
            // 'accmultavehi',
            // 'accmultaapu',
            // 'accmultapropa',
            // 'accmultarenta',
            // 'accmultalico',
            // 'accformucue',
            // 'accvincucue',
            // 'accrepplancue',
            // 'accrepvincucue',
            // 'accusuarioconta',
            // 'acctipoactivo',
            // 'accubicacionbien',
            // 'accmotivoincorporacion',
            // 'accmotivodesincorporacion',
            // 'accincorporacionmueble',
            // 'accincorporacioninmueble',
            // 'accdesincorporacionmueble',
            // 'accdesincorporacioninmueble',
            // 'acctransferenciabien',
            // 'accreptipoactivo',
            // 'accrepubicacionbien',
            // 'accrepdisposicion',
            // 'accrepincorporacion',
            // 'accrepdesincorporacion',
            // 'accreptransferencia',
            // 'accusuariobien',
            // 'acccargarcue',
            // 'accasiento',
            // 'status',
            // 'liquidador:boolean',
            // 'accmodreten',
            // 'accrepobras',
            // 'accenvchecausar',
            // 'poseeimpresora:boolean',
            // 'puerto',
            // 'accrepcatcue',
            // 'accrepsalini',
            // 'accrepsaldo',
            // 'accrepbalacom',
            // 'accrepbalagen',
            // 'accrepasiento',
            // 'accrepestamov',
            // 'accrepinvemueble',
            // 'accrepresuinvemueble',
            // 'accrepmovimueble',
            // 'accrepmresucuemue',
            // 'accrepmayoranali',
            // 'accacticontri',
            // 'impresora',
            // 'accadministrador',
            // 'idcoordinacion',
            // 'iddireccion',
            // 'rememberMe:boolean',

            ['class' => 'yii\grid\ActionColumn', 'header' => 'Acciones'],
        ],
    ]); ?>

</div>
